name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
        apt-packages: [libcups2-dev]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Flake8 and  Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.apt-packages }}
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
        pip uninstall pycrypto -y
        pip install pycryptodome==3.18.0
        
        
    - name: Run Tests
      run: |
        flake8 edc_offstudy
        python manage.py check
